-- ==============================================================================
-- SCENTÉ — Phase 3A: Product Catalog Seed Script
-- Idempotent upsert matching existing products.js dataset
-- ==============================================================================

-- 1. SCENTÉ NOIR
INSERT INTO public.products (
    id,
    slug,
    name,
    subtitle,
    tagline,
    description,
    concentration,
    family,
    families,
    olfactive_family,
    price,
    currency,
    volume,
    primary_image,
    secondary_image,
    mood,
    notes,
    fragrance_profile,
    stock_quantity,
    is_active
) VALUES (
    'scente-noir',
    'scente-noir',
    'SCENTÉ NOIR',
    'Extrait de Parfum',
    'Shadows woven in smoke and velvet.',
    'A dark, magnetic portrait of midnight architecture. SCENTÉ NOIR opens with dry smoked cardamom and chilled bergamot before yielding to a rich heart of Tuscan leather, dark plum, and Florentine iris, anchored on deep aged oud and Haitian vetiver.',
    '30% Pure Perfume Oil',
    'woody',
    '["woody", "amber"]'::jsonb,
    'Smoky Woods & Black Leather',
    12500,
    'PKR',
    '50ml / 1.7 FL. OZ.',
    'https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&w=1000&q=85',
    'https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&w=1000&q=85',
    'Smoky • Nocturnal • Magnetic',
    '{"top": ["Smoked Cardamom", "Calabrian Bergamot", "Pink Peppercorn"], "heart": ["Tuscan Leather", "Dark Plum", "Black Iris"], "base": ["Aged Oud", "Haitian Vetiver", "Smoky Amber Resins"]}'::jsonb,
    '{"scent_families": [], "intensity": null, "moods": [], "occasions": [], "seasons": []}'::jsonb,
    50,
    true
)
ON CONFLICT (id) DO UPDATE SET
    slug = EXCLUDED.slug,
    name = EXCLUDED.name,
    subtitle = EXCLUDED.subtitle,
    tagline = EXCLUDED.tagline,
    description = EXCLUDED.description,
    concentration = EXCLUDED.concentration,
    family = EXCLUDED.family,
    families = EXCLUDED.families,
    olfactive_family = EXCLUDED.olfactive_family,
    price = EXCLUDED.price,
    volume = EXCLUDED.volume,
    primary_image = EXCLUDED.primary_image,
    secondary_image = EXCLUDED.secondary_image,
    mood = EXCLUDED.mood,
    notes = EXCLUDED.notes,
    fragrance_profile = COALESCE(products.fragrance_profile, EXCLUDED.fragrance_profile),
    is_active = EXCLUDED.is_active,
    updated_at = NOW();

-- 2. SCENTÉ AMBER
INSERT INTO public.products (
    id,
    slug,
    name,
    subtitle,
    tagline,
    description,
    concentration,
    family,
    families,
    olfactive_family,
    price,
    currency,
    volume,
    primary_image,
    secondary_image,
    mood,
    notes,
    fragrance_profile,
    stock_quantity,
    is_active
) VALUES (
    'scente-amber',
    'scente-amber',
    'SCENTÉ AMBER',
    'Extrait de Parfum',
    'Liquid warmth at the hour of twilight.',
    'Inspired by the golden hour along Mediterranean coastlines. A warm, enveloping composition that fuses sun-drenched mandora and bitter almond with a molten core of ambergris, wild honey, and toasted Madagascar vanilla.',
    '32% Pure Perfume Oil',
    'amber',
    '["amber"]'::jsonb,
    'Radiant Amber & Sunlit Tonka',
    14500,
    'PKR',
    '50ml / 1.7 FL. OZ.',
    'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=1000&q=85',
    'https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&w=1000&q=85',
    'Warm • Radiant • Enveloping',
    '{"top": ["Sunlit Mandora", "Bitter Almond", "Spiced Amber Rum"], "heart": ["Ambergris Absolute", "Golden Honey", "Warm Cashmeran"], "base": ["Madagascar Vanilla Pod", "Roasted Tonka Bean", "Siam Benzoin"]}'::jsonb,
    '{"scent_families": [], "intensity": null, "moods": [], "occasions": [], "seasons": []}'::jsonb,
    50,
    true
)
ON CONFLICT (id) DO UPDATE SET
    slug = EXCLUDED.slug,
    name = EXCLUDED.name,
    subtitle = EXCLUDED.subtitle,
    tagline = EXCLUDED.tagline,
    description = EXCLUDED.description,
    concentration = EXCLUDED.concentration,
    family = EXCLUDED.family,
    families = EXCLUDED.families,
    olfactive_family = EXCLUDED.olfactive_family,
    price = EXCLUDED.price,
    volume = EXCLUDED.volume,
    primary_image = EXCLUDED.primary_image,
    secondary_image = EXCLUDED.secondary_image,
    mood = EXCLUDED.mood,
    notes = EXCLUDED.notes,
    fragrance_profile = COALESCE(products.fragrance_profile, EXCLUDED.fragrance_profile),
    is_active = EXCLUDED.is_active,
    updated_at = NOW();

-- 3. SCENTÉ MUSK
INSERT INTO public.products (
    id,
    slug,
    name,
    subtitle,
    tagline,
    description,
    concentration,
    family,
    families,
    olfactive_family,
    price,
    currency,
    volume,
    primary_image,
    secondary_image,
    mood,
    notes,
    fragrance_profile,
    stock_quantity,
    is_active
) VALUES (
    'scente-musk',
    'scente-musk',
    'SCENTÉ MUSK',
    'Extrait de Parfum',
    'An intimate whisper, close to the skin.',
    'A seamless second-skin fragrance. Pure white aldehydes meet freshly washed linen chords and powdery Tuscan orris, dissolving gently into comforting molecular musks and sun-bleached Virginian cedarwood.',
    '28% Pure Perfume Oil',
    'musk',
    '["musk"]'::jsonb,
    'Sensual Skin Musk & White Cedar',
    13500,
    'PKR',
    '50ml / 1.7 FL. OZ.',
    'https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?auto=format&fit=crop&w=1000&q=85',
    'https://images.unsplash.com/photo-1616949755610-8c9bbc08f138?auto=format&fit=crop&w=1000&q=85',
    'Clean • Sensual • Timeless',
    '{"top": ["White Aldehydes", "Bergamot Peel", "Pure Linen Accords"], "heart": ["Florentine Orris", "White Musk", "Heliotrope Petals"], "base": ["Iso E Super", "Virginian Cedarwood", "Warm Ambrette"]}'::jsonb,
    '{"scent_families": [], "intensity": null, "moods": [], "occasions": [], "seasons": []}'::jsonb,
    50,
    true
)
ON CONFLICT (id) DO UPDATE SET
    slug = EXCLUDED.slug,
    name = EXCLUDED.name,
    subtitle = EXCLUDED.subtitle,
    tagline = EXCLUDED.tagline,
    description = EXCLUDED.description,
    concentration = EXCLUDED.concentration,
    family = EXCLUDED.family,
    families = EXCLUDED.families,
    olfactive_family = EXCLUDED.olfactive_family,
    price = EXCLUDED.price,
    volume = EXCLUDED.volume,
    primary_image = EXCLUDED.primary_image,
    secondary_image = EXCLUDED.secondary_image,
    mood = EXCLUDED.mood,
    notes = EXCLUDED.notes,
    fragrance_profile = COALESCE(products.fragrance_profile, EXCLUDED.fragrance_profile),
    is_active = EXCLUDED.is_active,
    updated_at = NOW();

-- 4. PRODUCT VARIANTS (50ML STANDARD)
INSERT INTO public.product_variants (product_id, size, volume, price, stock_quantity, is_active)
VALUES 
    ('scente-noir', '50ml', '50ml / 1.7 FL. OZ.', 12500, 50, true),
    ('scente-amber', '50ml', '50ml / 1.7 FL. OZ.', 14500, 50, true),
    ('scente-musk', '50ml', '50ml / 1.7 FL. OZ.', 13500, 50, true)
ON CONFLICT (product_id, size) DO UPDATE SET
    price = EXCLUDED.price,
    volume = EXCLUDED.volume,
    stock_quantity = EXCLUDED.stock_quantity,
    is_active = EXCLUDED.is_active,
    updated_at = NOW();
